# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a84202b23a0ec2cad1f008a4ef056c58f95d16cb4da341f5219e4c706f8636763449acebf30e585e1d9dc3f032be1f992ab2ced03aba7cc611b34677c85d52be

test:
  secret_key_base: 712ab24ac804fbbaae7b0fadcf09150493c20f71415c4eeee7fdea9904cbe3c839eca69437f0c56cc09722f1106b51e2ffb8fa576b5d4ef0e0d3bc01bf2bc351

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
