# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 907c81d25c54c2a7c82ff38261a4f06328a6a9c00937a69d8fa20829a3f91cd002cfd9fe3a9c576c448b8c8ac4d24f598dfda1f3655e842c09a1efbffd511eb6

test:
  secret_key_base: c90d48a7bfe24855e2ce6b0008168385a5c6f8de7b402ea61eec7d62d1170e8ef5c932e7b182573452c68ebf06bf54b0702c7b3bdea09907f8a3af2cf795f8f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
