# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16fd0dc28cde3a6014b9c566a356c6c15e1f4e20397c6accf6e699eae4acb7a94bce3f802c74ee63e0c787b68da524f444681cc56f3e2c4885b78f53c0dae3b1

test:
  secret_key_base: 63342b05492f0cdc1c7934e619bb5c6970ea83a5478238b1fcd09d3ae647e584c9c823f3d4aeb318ddd776811b9364d33e0da645dcd2a5762a49afb8f5099879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
