# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebe257f3557669ac6e32103cd5016882504bd7501cb931a40e72815783a0748707081ba12d0c08db9e6f075f7365c08cb7433fdc65831f72e2d2ba451eb6b64d

test:
  secret_key_base: c54553f6b30e5632d9a9f88e9816bcbad7d7272d152378b6c9113c44c347f63d04883a3035dce366499ff461a280bd7b5ccaa0c305119f537eb514f3c7ba99df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
